List productData1 = [
  {
    'id' : 1,
    'name' : 'MackBook Air M1',
    'brand' : 'Apple',
    'img' : 'asset/images/Products/macBookAirM1.png',
    'price' : 999.9,
    'description' : 'Retina display\n13.3-inch (diagonal) LED-backlit display with IPS technology; 2560x1600 native resolution at 227 pixels per inch with support for millions of colours\nSupported scaled resolutions:\n1680x1050\n1440x900\n1024x640\n400 nits brightness\nWide colour (P3)\nTrue Tone technology',
    'rating' : 4.5,
    'review' : 2456,
    'like' : 94,
    'quantity' : 0,
    'inCart' : false,
    'favourite' : false
  },
  {
    'id' : 2,
    'name' : 'MackBook Pro M3',
    'brand' : 'Apple',
    'img' : 'asset/images/Products/macBookProM3.png',
    'price' : 2277,
    'description' : 'MacBook Pro 14-inch (M3, 2023) is a macOS laptop with a 14.20-inch display that has a resolution of 1964x3024 pixels. It is powered by a Apple M3 processor and it comes with 8GB of RAM. The MacBook Pro 14-inch (M3, 2023) packs 512GB of SSD storage.\nConnectivity options include Wi-Fi 802.11 ax, Bluetooth and it comes with 3 USB ports (3 x Thunderbolt 3 (Type C)), HDMI Port, Multi Card Slot, Headphone and Mic Combo Jack ports.',
    'rating' : 4.5,
    'review' : 1456,
    'like' : 98,
    'quantity' : 0,
    'inCart' : false,
    'favourite' : true
  },
  {
    'id' : 3,
    'name' : 'MackBook Pro M2',
    'brand' : 'Apple',
    'img' : 'asset/images/Products/MackBookProM2.png',
    'price' : 1505.9,
    'description' : 'Apple M2 chip\n8-core CPU with 4 performance cores and 4 efficiency cores\n10-core GPU\n16-core Neural Engine\n100GB/s memory bandwidth\nRetina display\n13.3-inch (diagonal) LED-backlit display with IPS technology; 2560x1600 native resolution at 227 pixels per inch with support for millions of colours\n500 nits brightness\nWide colour (P3)\nTrue Tone technology',
    'rating' : 4.0,
    'review' : 3500,
    'like' : 80,
    'quantity' : 0,
    'inCart' : false,
    'favourite' : true
  },
  {
    'id' : 4,
    'name' : 'MackBook Air M2',
    'brand' : 'Apple',
    'img' : 'asset/images/Products/MackBookAirM2.png',
    'price' : 1614.3,
    'description' : 'Apple M2 chip\n8-core CPU with 4 performance cores and 4 efficiency cores\n8-core GPU\n16-core Neural Engine\n100GB/s memory bandwidth\nConfigurable to M2 with 8-core CPU and 10-core GPULiquid\nRetina display\n13.6-inch (diagonal) LED-backlit display with IPS technology;1 2560x1664 native resolution at 224 pixels per inch\n500 nits brightness',
    'rating' : 4.5,
    'review' : 1432,
    'like' : 95,
    'quantity' : 0,
    'inCart' : false,
    'favourite' : false
  },
  {
    'id' : 5,
    'name' : 'Mac Mini M2',
    'brand' : 'Apple',
    'img' : 'asset/images/Products/MacMiniM2.png',
    'price' : 1457.7,
    'description' : 'M2 Pro chip for exceptional speed and performance\nUp to 12-core CPU packs up to 1.9x faster performance for editing massive images\nUp to 19-core GPU with up to 2.6x faster performance for video editing and 3D modelling\nPowerful media engine with support for H.264, HEVC, ProRes video\n16-core Neural Engine for advanced machine learning\n16GB or 32GB of unified memory, so everything you do is fast and fluid\nSuperfast SSD storage launches apps and opens files in an instant\nSupports up to three displays\nAdvanced cooling system sustains outstanding performance\nFast Wi-Fi 6E wireless connectivity\nFour Thunderbolt 4 ports, one HDMI port, two USB-A ports, headphone jack, Gigabit or 10Gb Ethernet\nUltra-compact 19.70 cm (7.7-inch) square design in silver\nmacOS Ventura gives you powerful new ways to get more done, share and collaborate — across all your Apple devices',
    'rating' : 5.0,
    'review' : 1423,
    'like' : 90,
    'quantity' : 0,
    'inCart' : false,
    'favourite' : false
  },
  {
    'id' : 6,
    'name' : 'Asus Vivobook 15',
    'brand' : 'Asus',
    'img' : 'asset/images/Products/AsusVivobook15.png',
    'price' : 649.3,
    'description' : 'Asus Vivobook 15 Summary\nAsus Vivobook 15 is a Windows 11 laptop with a 15.60-inch display. It is powered by a Core i5 processor and it comes with 8GB of RAM.\nConnectivity options include Bluetooth and it comes with USB 3.2 Gen 1 (Type A), USB 3.2 Gen 2 (Type C), HDMI Port, Mic In ports.\nAs of 11th February 2024, Asus Vivobook 15 price in India starts at Rs. 49,990.',
    'rating' : 4.5,
    'review' : 2417,
    'like' : 96,
    'quantity' : 0,
    'inCart' : false,
    'favourite' : true
  },
  {
    'id' : 7,
    'name' : 'HP Victus Gaming',
    'brand' : 'HP',
    'img' : 'asset/images/Products/HPVictusGaming.png',
    'price' : 685.5,
    'description' : 'Windows 11 HomeIntel® Core™ i5-13500H (up to 4.7 GHz, 18 MB L3 cache, 12 cores, 16 threads) + NVIDIA® GeForce RTX™ 3050 Laptop GPU (6 GB)8 GB DDR4-3200 SDRAM (2 X 4 GB)512 GB PCIe® NVMe™ TLC M.2 SSD (4x4 SSD)',
    'rating' : 4.2,
    'review' : 2862,
    'like' : 70,
    'quantity' : 0,
    'inCart' : false,
    'favourite' : false
  },
  {
    'id' : 8,
    'name' : 'Acer Nitro 16',
    'brand' : 'Acer',
    'img' : 'asset/images/Products/AcerNitro16.png',
    'price' : 1565.7,
    'description' : 'Powered by a 3.2 GHz AMD Ryzen 7 7735HS 8-Core processor and 16GB of DDR5 RAM, this gaming laptop can handle all your games and apps with ease. The 512GB SSD allows for fast boot and load times, so you can get into the action faster. The NVIDIA GeForce RTX 4070 features 8GB of GDDR6 VRAM and can provide real-time raytracing and DLSS support. The 16" IPS display features a QHD+ 2560 x 1600 resolution, a 16:10 aspect ratio, and a 165 Hz refresh rate. You can also output to an external display via HDMI 2.1.',
    'rating' : 4.7,
    'review' : 1278,
    'like' : 80,
    'quantity' : 0,
    'inCart' : false,
    'favourite' : false
  },
  {
    'id' : 9,
    'name' : 'HP Chrome X360',
    'brand' : 'HP',
    'img' : 'asset/images/Products/HPChromeX360.png',
    'price' : 325.1,
    'description' : 'Microprocessor : Intel® Core™ i3-8130U (2.2 GHz base frequency, up to 4 GHz with Intel® Turbo Boost Technology, 4 MB cache, 2 cores)\nMemory, standard : 8 GB DDR4-2400 SDRAM (onboard)\nVideo graphics : Intel® UHD Graphics 620 Integrated\nHard drive : 64 GB eMMC\nDisplay : 14" diagonal FHD IPS micro-edge WLED-backlit multitouch-enabled edge-to-edge glass (1920 x 1080)\nWireless connectivity : Intel® 802.11b/g/n/ac (2x2) Wi-Fi® and Bluetooth® 4.2 Combo\nExpansion slots : 1 microSD media card reader\nExternal ports : 2 USB 3.1 Gen 1 Type-C™ (Charging, power delivery, video, data); 2 USB 3.1 Gen 1 (HP Sleep and Charge); 1 headphone/microphone combo\nMinimum dimensions (W x D x H) : 32.54 x 22.68 x 1.6 cm\nWeight : 1.67 kg',
    'rating' : 4.6,
    'review' : 4253,
    'like' : 92,
    'quantity' : 0,
    'inCart' : false,
    'favourite' : true
  },
  {
    'id' : 10,
    'name' : 'Dell G15-5520',
    'brand' : 'Dell',
    'img' : 'asset/images/Products/DellG155520.png',
    'price' : 831.16,
    'description' : 'Dell G15 (5520) is a Windows 11 laptop with a 15.60-inch display that has a resolution of 1920x1080 pixels. It is powered by a Core i5 processor and it comes with 16GB of RAM.Graphics are powered by Nvidia GeForce RTX 3050. Connectivity options include Wi-Fi 802.11 a/b/g/n/ac/ax, Ethernet and it comes with 3 USB ports (1 x USB 3.1 Gen 1 (Type C)), USB 3.2 Gen 1 (Type A), HDMI Port, Headphone and Mic Combo Jack, RJ45 (LAN) ports.As of 11th February 2024, Dell G15 (5520) price in India starts at Rs. 68,990.',
    'rating' : 4.0,
    'review' : 4253,
    'like' : 99,
    'quantity' : 0,
    'inCart' : false,
    'favourite' : false
  },
  {
    'id' : 11,
    'name' : 'HP Laptop 15s',
    'brand' : 'HP',
    'img' : 'asset/images/Products/HPLaptop15s.png',
    'price' : 445.78,
    'description' : '【6-core 12th Gen Intel Core i3-1215U】 8 threads and 10MB L3 cache deliver high performance and instant responsiveness. The Intel UHD graphics help you dive into crisp, stunning visuals.\n【Upgraded memory and storage】 8GB DDR4 RAM and 512GB SSD help you undertake improved multitasking with ample of storage and higher-bandwidth memory. Now, create, browse, and work as you please.\n【Micro-edge display】 The 15.6-inch, FHD, micro-edge, EPEAT registered, ENERGY STAR certified, 250-nit, and anti-glare display helps you see more of what’s on your screen in great quality.\n【Effortless connectivity】 Wi-Fi 5 (2x2) and Bluetooth 5.0 help you be unstoppable with fast speeds. Experience reliable connectivity with 1 x USB Type-C, 2 x USB Type-A, and 1 x HDMI 1.4b ports.\n【Long battery life】 Fast charging 0% to 50% in 45 mins, up to 7 hours and 45 mins of battery life and up to 10 hours and 45 mins of video playback help you stay productive without frequent charging.',
    'rating' : 4.5,
    'review' : 2456,
    'like' : 94,
    'quantity' : 0,
    'inCart' : false,
    'favourite' : false
  },
  {
    'id' : 12,
    'name' : 'Apple iPad 10Gen',
    'brand' : 'Apple',
    'img' : 'asset/images/Products/iPad10Gen.png',
    'price' : 451.80,
    'description' : 'PadOS + APPS — iPadOS makes iPad more productive, intuitive and versatile. With iPadOS, run multiple apps at once, use Apple Pencil to write in any text field with Scribble, and edit and share photos. iPad comes with essential apps like Safari, Messages and Keynote, with over a million more apps available on the App Store.\nFAST WI-FI CONNECTIVITY — Wi-Fi 6 gives you fast access to your files, uploads and downloads, and lets you seamlessly stream your favourite shows.\nPERFORMANCE AND STORAGE — The A14 Bionic chip delivers power and performance for any activity. And with all-day battery life, iPad is perfect for playing immersive games and editing photos and videos. Choose from 64GB or 256GB storage options.',
    'rating' : 4.5,
    'review' : 1456,
    'like' : 98,
    'quantity' : 0,
    'inCart' : false,
    'favourite' : true
  },
  {
    'id' : 13,
    'name' : 'Apple iPhone 15',
    'brand' : 'Apple',
    'img' : 'asset/images/Products/AppleiPhone15.png',
    'price' : 927.72,
    'description' : 'DYNAMIC ISLAND COMES TO IPHONE 15 — Dynamic Island bubbles up alerts and Live Activities — so you don’t miss them while you’re doing something else. You can see who’s calling, track your next ride, check your flight status, and so much more.\nINNOVATIVE DESIGN — iPhone 15 features a durable color-infused glass and aluminum design. It’s splash, water, and dust resistant. The Ceramic Shield front is tougher than any smartphone glass. And the 6.1" Super Retina XDR display is up to 2x brighter in the sun compared to iPhone 14.\n48MP MAIN CAMERA WITH 2X TELEPHOTO — The 48MP Main camera shoots in super-high resolution. So it’s easier than ever to take standout photos with amazing detail. The 2x optical-quality Telephoto lets you frame the perfect close-up.\nNEXT-GENERATION PORTRAITS — Capture portraits with dramatically more detail and color. Just tap to shift the focus between subjects — even after you take the shot.\nPOWERHOUSE A16 BIONIC CHIP — The superfast chip powers advanced features like computational photography, fluid Dynamic Island transitions, and Voice Isolation for phone calls. And A16 Bionic is incredibly efficient to help deliver great all-day battery life.',
    'rating' : 4.0,
    'review' : 3500,
    'like' : 80,
    'quantity' : 0,
    'inCart' : false,
    'favourite' : true
  },
  {
    'id' : 14,
    'name' : 'OnePlus 11R 5G',
    'brand' : 'OnePlus',
    'img' : 'asset/images/Products/OnePlus11R5G.png',
    'price' : 542.17,
    'description' : 'Camera: Sensor: 50MP Main Camera with Sony IMX890 (OIS supported), 8MP Ultrawide Camera (FOV: 120 degree) and Macro Lens; 16MP Front (Selfie) Camera with EIS support\nCamera Modes: Nightscape, Ultra HDR, Smart Scene Recognition, Portrait Mode, Pro Mode, Panorama, Tilt-Shift mode, Long Exposure, Dual-View Video, Retouch, Movie Mode, Raw file, Filters, Super Stable, Video Nightscape, Video HDR, Video Portrait, Focus Tracking, Timelapse, Macro modeDisplay: 6.7 Inches; 120 Hz Super Fluid AMOLED; Resolution: 2772 X 1240 pixels ,450 ppi, 20.1:9, 10-bit Color Depth, HDR10+nOperating System: OxygenOS based on Android 13\nProcessor: Snapdragon 8+ Gen 1 Mobile Platform',
    'rating' : 4.5,
    'review' : 1432,
    'like' : 95,
    'quantity' : 0,
    'inCart' : false,
    'favourite' : false
  },
  {
    'id' : 15,
    'name' : 'Lenovo IdeaPad',
    'brand' : 'Lenovo',
    'img' : 'asset/images/Products/LenovoIdeaPad.png',
    'price' : 406.63,
    'description' : 'Processor: Intel Core i3 - 1215U | Speed: 1.2GHz (Base) - 4.4GHz (Max) | 6 Cores | 8 Threads | 10MB Cache\nDisplay: 15.6" FHD (1920x1080) | TN | 250nits Brigthness | Anti-glare\nOS and Software: Windows 11 Home 64 | Office Home and Student 2021 | Xbox GamePass Ultimate 3-month subscription*\nGraphics: Integrated Intel UHD Graphics || Memory: 8GB DDR4-3200 | upgradable Up to 16GB || Storage: 256 GB SSD\nDesign: 1.99 cm Thin and 1.63 kg Light | Non-backlit Keyboard | 4 Side Narrow Bezel\nBattery Life: 45Wh | Upto 5 Hours | Rapid Charge (get 2 hours of runtime with a 15-minute charge) || Connectivity: Wi-Fi 6 (11ax | 2x2) | Bluetooth: BT5.1\nCamera: HD 720p with Privacy Shutter | Fixed Focus | Integrated Dual Array Microphone || Audio: 2x 1.5W Stereo Speakers | HD Audio | Dolby Audio',
    'rating' : 5.0,
    'review' : 1423,
    'like' : 90,
    'quantity' : 0,
    'inCart' : false,
    'favourite' : false
  },
  {
    'id' : 16,
    'name' : 'Nokia C22',
    'brand' : 'Nokia',
    'img' : 'asset/images/Products/NokiaC22.png',
    'price' : 78.30,
    'description' : 'Rigorously tested for durability with its unibody design, toughened display glass and IP52 protection¹ rating, it’s better protected against drops, dust, and spills.\nThe huge 5000 mAh battery³ goes further thanks to the latest battery-saving features.\nTake perfect shots day or night thanks to bespoke imaging algorithms that bring powerful Night and Portrait modes to both the dual 13 MP rear camera and the 8 MP selfie camera.\nStunning 6.5” HD+ display with brightness boost.\nOcta-core chipset with 2GB of additional virtual RAM for smooth user experience.',
    'rating' : 4.5,
    'review' : 2417,
    'like' : 96,
    'quantity' : 0,
    'inCart' : false,
    'favourite' : true
  },
  {
    'id' : 17,
    'name' : 'iQOO 12 5G',
    'brand' : 'iQOO',
    'img' : 'asset/images/Products/iQOO125G.png',
    'price' : 638.55,
    'description' : '3.3 GHz Snapdragon 8 Gen 3 mobile platform, which is on 4nm TSMC Process. Enhanced graphic performance with Adreno 750. In addition to that, it has LPDRR5X RAM & UFS 4.0 storage.\n50MP 1/1.3" Astrography Camera (f/1.68) + 50MP Ultra - Wide Angle Camera (f/1.20) + 64MP 3X Periscope Telephoto Camera (f/2.57) with 100X Digital zoom.\nBrightest Display ever with 6.78" 144 Hz LTPO AMOLED display with 3000 nit peak brightness. SGS-certified for low blue light. 2160Hz PWM uses the persistence of human vision to control display brightness.\nSupercomputing chip Q1, Symmetrical dual stereo speaker, 4D Game vibration, Large X-axis linear motor enhances the overall gaming experience.\nFully charged battery with 120W fast charger. IP64 rating provides ingress protection against dust/water under normal use. Funtouch OS 14 based on Android 14',
    'rating' : 4.2,
    'review' : 2862,
    'like' : 70,
    'quantity' : 0,
    'inCart' : false,
    'favourite' : false
  },
  {
    'id' : 18,
    'name' : 'iQOO Neo 7 Pro 5G',
    'brand' : 'iQOO',
    'img' : 'asset/images/Products/iQOONeo7Pro5G.png',
    'price' : 409.63,
    'description' : 'Snapdragon 8+ Gen 1 Mobile Platform adopts TSMC 4nm Process & has Superior Flagship Grade Performance with LPDDR5 RAM & UFS 3.1 Storage\nIndependent Gaming Chip boosts FPS by Game Frame Interpolation, sharpens Display with Game Display Enhancement and reduces power consumption\nTakes only 8 min to charge from 1% to 50% with 120W FlashCharge in Fast Charging Mode (100% in 25 min)\nUtmost clarity whether it’s Day or Night with Flagship 50MP GN5 OIS Ultra-Sensing coupled with Ultra-Wide (8MP) and Macro Camera\nMotion Control, Gyroscope Enhancement, 4D Game Vibration, Voice Changer are here to level up your gaming experience',
    'rating' : 4.7,
    'review' : 1278,
    'like' : 80,
    'quantity' : 0,
    'inCart' : false,
    'favourite' : false
  },
  {
    'id' : 19,
    'name' : 'realme 12 Pro 5G',
    'brand' : 'realMe',
    'img' : 'asset/images/Products/realme12Pro5G.png',
    'price' : 300.61,
    'description' : 'Embark on a journey of photography excellence with the realme 12 Pro 5G\'s unmatched 32 MP 2X Flagship Telephoto Portrait Camera. In a league of its own, this camera brings 2x optical zoom and 4x lossless zoom to the forefront, delivering superior sharpness, noise control, and dynamic range that leaves rivals behind.\nTransform your photography with the realme 12 Pro 5G\'s pioneering 50 MP SONY IMX882 OIS Camera. Boasting the largest sensor in its segment, this camera crafts unmatched HDR and nightscape brilliance. Bid farewell to blur with SuperOIS, while the Ultra Clarity Engine and DIS Engine ensure unparalleled precision. Elevate your photography game with this game-changing device that captures moments with unprecedented clarity\nPowered by the Qualcomm Snapdragon 6 Gen1, the realme 12 Pro 5G stands out with the only 4 nm Snapdragon chipset in its segment with 5G compatibility. This smartphone ensures powerful performance, allowing the smooth completion of all your tasks. From lag-free gaming to seamless multitasking, experience the cutting-edge capabilities of this chipset.\nmmerse yourself in the fusion of technology and elegance with the realme 12 Pro 5G\'s Luxury Watch Design. Crafted in collaboration with master watchmaker Ollivier Savelli, this smartphone integrates classic luxury watch elements. Featuring a precision Dial, Golden Fluted Bezel, and intricate textures reminiscent of high-end watch craftsmanship, this series ushers in a new era of light luxury.\nExperience brilliance on the realme 12 Pro 5G\'s 120 Hz Curved Vision OLED display! The swift 16× HyperPrecise Touch ensures lightning-fast and accurate responses, while ProXDR restores HDR\'s full dynamic range for unparalleled photo viewing. With 2160 Hz PWM dimming and AI brightness adjustment for superior visual comfort, this display is an eye-friendly treat.\nnjoy peak performance without the heat, thanks to the realme 12 Pro 5G\'s 3D Vapour Chamber Cooling System. The spacious stainless steel vapour chamber increases the heat dissipation area, ensuring top-notch performance while maintaining an optimal temperature. Say goodbye to overheating worries and embrace a seamless user\nPower up at lightning speed with the 67 W SUPERVOOC Charge and revel in extended usage with the robust 5000 mAh battery. Stay connected longer with reduced wait times. The dual charge pump technology and intelligent five-core chip protection ensure optimal charging efficiency and top-tier device safety.\nSeamlessly multitask with an impressive 8 GB + 8 GB of Dynamic RAM and enjoy ample space for photos, videos, and documents with up to 256 GB of storage. The DRE dynamic memory expansion technology allows you to convert ROM into RAM, enhancing the smartphone\'s overall performance.',
    'rating' : 4.6,
    'review' : 4253,
    'like' : 92,
    'quantity' : 0,
    'inCart' : false,
    'favourite' : true
  },
  {
    'id' : 20,
    'name' : 'Xiaomi Pad 6',
    'brand' : 'Xiaomi',
    'img' : 'asset/images/Products/XiaomiPad6.png',
    'price' : 337.34,
    'description' : 'Snapdragon 870 Octa-Core Processor | Adreno 650 | Qualcomm AI engine | LPDDR5 RAM | UFS 3.1 | Up to 8GB RAM\n144Hz 7-Stage Refresh Rate | 27.9cm(11) Display | 2.8K Resolution | 1 Billion Colors | 2880*1800 High Resolution\nQuad Speakers with Dolby Atmos | Long Lasting 8840mAh Battery | Android 13 | MIUI 14 with Android & Security Updates\n8MP Front Camera with Focus Frame | 13MP Rear Camera | Metal Unibody Design',
    'rating' : 4.0,
    'review' : 4253,
    'like' : 99,
    'quantity' : 0,
    'inCart' : false,
    'favourite' : false
  },
];